"""add cloud sync v2 foundation tables

Revision ID: 0011_cloud_sync_v2_foundations
Revises: 0010_workspace_idempotency, 0010_hot_path_indexes
Create Date: 2026-05-26 00:00:00
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0011_cloud_sync_v2_foundations"
down_revision: Union[str, Sequence[str], None] = ("0010_workspace_idempotency", "0010_hot_path_indexes")
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "workspace_change_sequences",
        sa.Column("workspace_id", sa.Integer(), sa.ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False),
        sa.Column("stream", sa.String(length=32), nullable=False),
        sa.Column("seq", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("workspace_id", "stream"),
    )

    op.execute(
        """
        CREATE TABLE workspace_change_log (
            workspace_id INTEGER NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
            stream VARCHAR(32) NOT NULL,
            seq BIGINT NOT NULL,
            kind VARCHAR(64) NOT NULL,
            ref_id VARCHAR(128) NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            PRIMARY KEY (workspace_id, stream, seq, created_at)
        ) PARTITION BY RANGE (created_at)
        """
    )
    op.execute(
        """
        CREATE TABLE workspace_change_log_default
        PARTITION OF workspace_change_log DEFAULT
        """
    )
    op.create_index(
        "idx_workspace_change_log_default_lookup",
        "workspace_change_log_default",
        ["workspace_id", "stream", "seq"],
    )

    op.create_table(
        "cloud_idempotency_keys",
        sa.Column("workspace_id", sa.Integer(), sa.ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False),
        sa.Column("scope", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("workspace_id", "scope", "idempotency_key"),
    )

    op.create_table(
        "sync_batches",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.Integer(), sa.ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="accepted", nullable=False),
        sa.Column("accepted_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("rejected_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "idempotency_key", name="uq_sync_batches_workspace_idempotency"),
    )
    op.create_index("idx_sync_batches_workspace_status", "sync_batches", ["workspace_id", "status", "created_at"])

    op.execute(
        """
        CREATE TABLE sync_batch_items (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            batch_id VARCHAR(36) NOT NULL,
            workspace_id INTEGER NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
            stream VARCHAR(32) NOT NULL,
            partition_key VARCHAR(256) NOT NULL,
            virtual_shard INTEGER NOT NULL,
            seq INTEGER NOT NULL,
            event_type VARCHAR(64) NOT NULL,
            idempotency_key VARCHAR(128) NOT NULL,
            payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            status VARCHAR(32) NOT NULL DEFAULT 'pending',
            worker_id VARCHAR(128),
            leased_until TIMESTAMPTZ,
            attempts INTEGER NOT NULL DEFAULT 0,
            last_error TEXT,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            PRIMARY KEY (id, created_at),
            UNIQUE (workspace_id, idempotency_key, created_at)
        ) PARTITION BY RANGE (created_at)
        """
    )
    op.execute(
        """
        CREATE TABLE sync_batch_items_default
        PARTITION OF sync_batch_items DEFAULT
        """
    )
    op.create_index(
        "idx_sync_batch_items_default_claim",
        "sync_batch_items_default",
        ["status", "virtual_shard", "created_at", "id"],
    )
    op.create_index(
        "idx_sync_batch_items_default_workspace_status",
        "sync_batch_items_default",
        ["workspace_id", "status", "created_at"],
    )
    op.create_index(
        "idx_sync_batch_items_default_partition_order",
        "sync_batch_items_default",
        ["workspace_id", "partition_key", "seq"],
    )

    op.create_table(
        "sync_worker_shard_leases",
        sa.Column("virtual_shard", sa.Integer(), nullable=False),
        sa.Column("worker_id", sa.String(length=128), nullable=False),
        sa.Column("leased_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("virtual_shard"),
    )
    op.create_index("idx_sync_worker_shard_leases_worker", "sync_worker_shard_leases", ["worker_id", "leased_until"])
    op.create_index("idx_sync_worker_shard_leases_expiry", "sync_worker_shard_leases", ["leased_until"])

    op.create_table(
        "workspace_rate_limits",
        sa.Column("workspace_id", sa.Integer(), sa.ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False),
        sa.Column("bucket", sa.String(length=64), nullable=False),
        sa.Column("tokens", sa.Float(), nullable=False),
        sa.Column("capacity", sa.Float(), nullable=False),
        sa.Column("refill_rate_per_second", sa.Float(), nullable=False),
        sa.Column("last_refill_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("workspace_id", "bucket"),
    )

    op.create_table(
        "sync_dead_letters",
        sa.Column("id", sa.BigInteger(), sa.Identity(), nullable=False),
        sa.Column("item_id", sa.BigInteger(), nullable=False),
        sa.Column("item_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.Integer(), sa.ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False),
        sa.Column("batch_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("partition_key", sa.String(length=256), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_sync_dead_letters_workspace_created", "sync_dead_letters", ["workspace_id", "created_at"])

    op.create_table(
        "dead_letter_attempts",
        sa.Column("id", sa.BigInteger(), sa.Identity(), nullable=False),
        sa.Column("dead_letter_id", sa.BigInteger(), sa.ForeignKey("sync_dead_letters.id", ondelete="CASCADE"), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_dead_letter_attempts_dead_letter", "dead_letter_attempts", ["dead_letter_id", "created_at"])

    op.create_table(
        "object_manifests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.Integer(), sa.ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("storage_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("compression", sa.String(length=32), server_default="none", nullable=False),
        sa.Column("ref_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_after", sa.DateTime(timezone=True)),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "sha256", name="uq_object_manifests_workspace_sha256"),
    )
    op.create_index("idx_object_manifests_workspace_status", "object_manifests", ["workspace_id", "status", "created_at"])

    op.create_table(
        "object_upload_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.Integer(), sa.ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("storage_provider_upload_id", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("part_size_bytes", sa.Integer(), nullable=False),
        sa.Column("parts_total", sa.Integer(), nullable=False),
        sa.Column("parts_completed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "sha256", "size_bytes", name="uq_object_upload_sessions_workspace_object"),
    )
    op.create_index("idx_object_upload_sessions_status_expires", "object_upload_sessions", ["status", "expires_at"])

    op.create_table(
        "object_upload_parts",
        sa.Column("session_id", sa.String(length=36), sa.ForeignKey("object_upload_sessions.id", ondelete="CASCADE"), nullable=False),
        sa.Column("part_number", sa.Integer(), nullable=False),
        sa.Column("etag", sa.Text()),
        sa.Column("size_bytes", sa.Integer()),
        sa.Column("sha256", sa.String(length=64)),
        sa.Column("completed_at", sa.DateTime(timezone=True)),
        sa.PrimaryKeyConstraint("session_id", "part_number"),
    )

    op.execute(
        """
        CREATE TABLE agent_commands (
            id VARCHAR(36) NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            workspace_id INTEGER NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
            target_device_id VARCHAR(256),
            target_role VARCHAR(64),
            status VARCHAR(32) NOT NULL DEFAULT 'pending',
            visibility_until TIMESTAMPTZ,
            idempotency_key VARCHAR(128) NOT NULL,
            payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            cancel_requested_at TIMESTAMPTZ,
            expires_at TIMESTAMPTZ NOT NULL,
            PRIMARY KEY (id, created_at),
            UNIQUE (workspace_id, idempotency_key, created_at)
        ) PARTITION BY RANGE (created_at)
        """
    )
    op.execute(
        """
        CREATE TABLE agent_commands_default
        PARTITION OF agent_commands DEFAULT
        """
    )
    op.create_index(
        "idx_agent_commands_default_dispatch",
        "agent_commands_default",
        ["workspace_id", "target_device_id", "status", "visibility_until"],
    )

    op.create_table(
        "agent_result_chunks",
        sa.Column("command_id", sa.String(length=36), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("is_final", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("command_id", "seq"),
    )
    op.create_index("idx_agent_result_chunks_created", "agent_result_chunks", ["created_at"])

    op.create_table(
        "article_versions",
        sa.Column("id", sa.BigInteger(), sa.Identity(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), sa.ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False),
        sa.Column("article_id", sa.BigInteger(), sa.ForeignKey("articles.id", ondelete="CASCADE"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("inline_text", sa.Text()),
        sa.Column("content_object_id", sa.String(length=36)),
        sa.Column("content_sha256", sa.String(length=64)),
        sa.Column("size_bytes", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("article_id", "version", name="uq_article_versions_article_version"),
    )
    op.create_index("idx_article_versions_workspace_article", "article_versions", ["workspace_id", "article_id", "version"])

    op.create_table(
        "articles_migration_state",
        sa.Column("article_id", sa.BigInteger(), sa.ForeignKey("articles.id", ondelete="CASCADE"), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="pending", nullable=False),
        sa.Column("sha256", sa.String(length=64)),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.Text()),
        sa.Column("completed_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("article_id"),
    )
    op.create_index("idx_articles_migration_state_status", "articles_migration_state", ["status", "updated_at"])


def downgrade() -> None:
    op.drop_index("idx_articles_migration_state_status", table_name="articles_migration_state")
    op.drop_table("articles_migration_state")
    op.drop_index("idx_article_versions_workspace_article", table_name="article_versions")
    op.drop_table("article_versions")
    op.drop_index("idx_agent_result_chunks_created", table_name="agent_result_chunks")
    op.drop_table("agent_result_chunks")
    op.drop_index("idx_agent_commands_default_dispatch", table_name="agent_commands_default")
    op.execute("DROP TABLE agent_commands")
    op.drop_table("object_upload_parts")
    op.drop_index("idx_object_upload_sessions_status_expires", table_name="object_upload_sessions")
    op.drop_table("object_upload_sessions")
    op.drop_index("idx_object_manifests_workspace_status", table_name="object_manifests")
    op.drop_table("object_manifests")
    op.drop_index("idx_dead_letter_attempts_dead_letter", table_name="dead_letter_attempts")
    op.drop_table("dead_letter_attempts")
    op.drop_index("idx_sync_dead_letters_workspace_created", table_name="sync_dead_letters")
    op.drop_table("sync_dead_letters")
    op.drop_table("workspace_rate_limits")
    op.drop_index("idx_sync_worker_shard_leases_expiry", table_name="sync_worker_shard_leases")
    op.drop_index("idx_sync_worker_shard_leases_worker", table_name="sync_worker_shard_leases")
    op.drop_table("sync_worker_shard_leases")
    op.drop_index("idx_sync_batch_items_default_partition_order", table_name="sync_batch_items_default")
    op.drop_index("idx_sync_batch_items_default_workspace_status", table_name="sync_batch_items_default")
    op.drop_index("idx_sync_batch_items_default_claim", table_name="sync_batch_items_default")
    op.execute("DROP TABLE sync_batch_items")
    op.drop_index("idx_sync_batches_workspace_status", table_name="sync_batches")
    op.drop_table("sync_batches")
    op.drop_table("cloud_idempotency_keys")
    op.drop_index("idx_workspace_change_log_default_lookup", table_name="workspace_change_log_default")
    op.execute("DROP TABLE workspace_change_log")
    op.drop_table("workspace_change_sequences")
