#!/usr/bin/env python3
"""Rank a target brand inside AI answer text stored in an Excel workbook.

The extractor is intentionally rule-based and evidence-first. It handles the
Markdown-like answers generated by common chat products: numbered headings,
tables, bullet lists, and compact "quick conclusion" paragraphs.
"""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

try:
    import openpyxl
    from openpyxl.comments import Comment
except ImportError as exc:  # pragma: no cover - exercised only in missing envs
    raise SystemExit(
        "Missing dependency: openpyxl. Install it with `pip install openpyxl`."
    ) from exc


DEFAULT_ANSWER_HEADERS = ("回答问题", "AI回答", "回答", "答案", "内容")
DEFAULT_RESULT_HEADERS = ("品牌位置", "排名", "位置")
LOW_CONFIDENCE_KINDS = {"mention", "bullet_order", "inline_category", "compressed_table_cell_order"}

LIST_START_RE = re.compile(r"^\s*(?:[-*+•]\s+|[（(]?[0-9一二三四五六七八九十]+[)）.、．]\s+)")
MARKDOWN_HEADING_RE = re.compile(r"^\s*(#{2,6})\s+(.+?)\s*$")
ANY_NUMBERED_RE = re.compile(
    r"(?:^|\s|[#>])(?:TOP\s*)?([0-9]{1,2})\s*(?:[.、．名位\)]|$)|第\s*([一二三四五六七八九十两0-9]{1,3})\s*(?:名|位|梯队|档)"
)
LEADING_NUMBERED_RE = re.compile(
    r"^\s*(?:[-*+•]\s*)?(?:#{1,6}\s*)?(?:TOP\s*)?([0-9]{1,2})\s*(?:[.、．名位\)]|\s|$)"
    r"|^\s*(?:[-*+•]\s*)?(?:#{1,6}\s*)?第\s*([一二三四五六七八九十两0-9]{1,3})\s*(?:名|位|梯队|档)"
)
TABLE_SEPARATOR_RE = re.compile(r"^\s*\|?\s*:?-{3,}:?\s*(?:\|\s*:?-{3,}:?\s*)+\|?\s*$")
HEADING_RE = re.compile(r"^\s*#{1,6}\s+")
PRODUCT_LIKE_RE = re.compile(
    r"([A-Za-z0-9\u4e00-\u9fff®·/]{2,36}(?:精华|次抛|面膜|敷料|修护液|乳液|原液|安瓶|乳|霜|水|棒))"
)
COMBO_SIGNAL_RE = re.compile(r"(?:组合|搭配|套装|方案|联合|早晚|日间|夜间|全周期)")
BUDGET_LABEL_RE = re.compile(
    r"(?:[<>≤≥]?\s*\d+\s*元\s*(?:以内|以下|以上|内)?|\d+\s*[-~—至]\s*\d+\s*元)"
)
RANKED_CONTEXT_RE = re.compile(r"(?:TOP\s*\d*|排名|排行|榜|名次|排序|优先推荐)", re.I)
NON_RANK_LABELS = (
    "核心成分",
    "核心技术",
    "技术亮点",
    "功效亮点",
    "核心功效",
    "核心数据",
    "临床数据",
    "使用体验",
    "性价比",
    "价格",
    "价格区间",
    "适配人群",
    "适用人群",
    "适合人群",
    "使用建议",
    "注意事项",
    "作用原理",
    "明星产品",
    "代表产品",
    "核心优势",
    "优势",
    "亮点",
    "资质",
    "认证",
)
RANKABLE_LABEL_RE = re.compile(
    r"(?:首选|推荐|选|品牌|产品|预算|价格|元|以内|以上|肤质|需求|场景|功效|类型|分类|适合|人群|抗老|抗衰|修护|淡纹|美白|补水|敏感|干皮|油皮|熟龄|初老)"
)
CHINESE_NUMBERS = {
    "零": 0,
    "一": 1,
    "二": 2,
    "两": 2,
    "三": 3,
    "四": 4,
    "五": 5,
    "六": 6,
    "七": 7,
    "八": 8,
    "九": 9,
    "十": 10,
}


@dataclass(frozen=True)
class RankHit:
    rank: int
    confidence: int
    kind: str
    evidence: str
    line_no: int


def main() -> int:
    args = parse_args()
    aliases = [args.brand]
    if args.alias:
        aliases.extend(args.alias)

    summary = rank_workbook(
        args.input,
        brand=args.brand,
        aliases=aliases,
        sheet=args.sheet,
        answer_col=args.answer_col,
        output_col=args.output_col,
        output=args.output,
        start_row=args.start_row,
        evidence=args.evidence,
        review=args.review,
        review_threshold=args.review_threshold,
    )
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    return 0


def rank_workbook(
    input_file: str | Path,
    *,
    brand: str,
    aliases: list[str] | None = None,
    sheet: str | None = None,
    answer_col: str | None = None,
    output_col: str | None = None,
    output: str | Path | None = None,
    start_row: int = 2,
    evidence: bool = True,
    review: bool = True,
    review_threshold: int = 75,
) -> dict:
    input_path = Path(input_file).expanduser().resolve()
    if not input_path.exists():
        raise SystemExit(f"Input file does not exist: {input_path}")

    aliases = dedupe_keep_order([a.strip() for a in (aliases or [brand]) if a.strip()])

    workbook = openpyxl.load_workbook(input_path)
    worksheet = workbook[sheet] if sheet else workbook.active

    headers = read_headers(worksheet)
    answer_col_index = resolve_column(answer_col, headers, DEFAULT_ANSWER_HEADERS)
    if not answer_col_index:
        raise SystemExit(
            "Could not find answer column. Use --answer-col, for example --answer-col 回答问题."
        )

    if output_col:
        rank_col = ensure_column(worksheet, output_col)
    else:
        rank_col = find_or_create_output_column(
            worksheet,
            f"{brand}排名",
            near_col=resolve_column(None, headers, DEFAULT_RESULT_HEADERS) or answer_col_index,
        )

    evidence_col = None
    if evidence:
        evidence_col = find_or_create_output_column(
            worksheet,
            f"{brand}排名证据",
            near_col=rank_col,
        )
    review_col = None
    if review:
        review_col = find_or_create_output_column(
            worksheet,
            f"{brand}复核建议",
            near_col=evidence_col or rank_col,
        )

    worksheet.cell(row=1, column=rank_col).value = f"{brand}排名"
    if evidence_col:
        worksheet.cell(row=1, column=evidence_col).value = f"{brand}排名证据"
    if review_col:
        worksheet.cell(row=1, column=review_col).value = f"{brand}复核建议"

    rows = []
    counts: dict[int, int] = {}
    review_count = 0
    for row in range(start_row, worksheet.max_row + 1):
        answer = cell_text(worksheet.cell(row=row, column=answer_col_index).value)
        result = rank_brand(answer, aliases)
        rank = result.rank if result else 0
        counts[rank] = counts.get(rank, 0) + 1
        worksheet.cell(row=row, column=rank_col).value = rank
        if evidence_col:
            evidence = result.evidence if result else "未发现目标品牌"
            worksheet.cell(row=row, column=evidence_col).value = evidence
            worksheet.cell(row=row, column=evidence_col).comment = Comment(evidence[:32000], "Codex")
        review_note = review_message(result, review_threshold) if result else ""
        if review_note:
            review_count += 1
        if review_col:
            worksheet.cell(row=row, column=review_col).value = review_note
        rows.append(
            {
                "row": row,
                "rank": rank,
                "kind": result.kind if result else "not_found",
                "confidence": result.confidence if result else 0,
                "evidence": result.evidence if result else "",
                "review": review_note,
            }
        )

    if output:
        output_path = Path(output).expanduser().resolve()
    else:
        output_path = default_output_path(input_path, brand)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    workbook.save(output_path)

    return {
        "input": str(input_path),
        "output": str(output_path),
        "sheet": worksheet.title,
        "brand": brand,
        "aliases": aliases,
        "answer_column": answer_col_index,
        "rank_column": rank_col,
        "evidence_column": evidence_col,
        "review_column": review_col,
        "processed_rows": max(0, worksheet.max_row - start_row + 1),
        "rank_counts": dict(sorted(counts.items())),
        "review_count": review_count,
        "samples": rows[:10],
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Fill per-row brand ranking results for AI answer text in an Excel workbook."
    )
    parser.add_argument("input", help="Path to the .xlsx workbook.")
    parser.add_argument("--brand", required=True, help="Target brand, for example 可复美.")
    parser.add_argument(
        "--alias",
        action="append",
        default=[],
        help="Additional brand alias. Can be passed multiple times.",
    )
    parser.add_argument("--sheet", help="Worksheet name. Defaults to the first sheet.")
    parser.add_argument(
        "--answer-col",
        help="Answer column header name, column letter, or 1-based column number.",
    )
    parser.add_argument(
        "--output-col",
        help="Output column header name, column letter, or 1-based column number.",
    )
    parser.add_argument("--output", help="Output .xlsx path. Defaults to exports/brand_ranker/.")
    parser.add_argument("--start-row", type=int, default=2, help="First data row. Defaults to 2.")
    parser.add_argument(
        "--no-evidence",
        dest="evidence",
        action="store_false",
        help="Do not add an evidence column.",
    )
    parser.add_argument(
        "--no-review",
        dest="review",
        action="store_false",
        help="Do not add a review suggestion column.",
    )
    parser.add_argument(
        "--review-threshold",
        type=int,
        default=75,
        help="Flag rank hits below this confidence for review. Defaults to 75.",
    )
    parser.set_defaults(evidence=True)
    parser.set_defaults(review=True)
    return parser.parse_args()


def rank_brand(answer: str, aliases: list[str]) -> RankHit | None:
    if not answer or not any(alias in answer for alias in aliases):
        return None

    hits = collect_rank_hits(answer, aliases)
    if hits:
        return choose_rank_hit(hits)

    return None


def review_message(result: RankHit, threshold: int) -> str:
    if result.confidence < threshold:
        return f"需复核：低置信度 {result.confidence}（{result.kind}）"
    if result.kind in LOW_CONFIDENCE_KINDS:
        return f"建议抽查：{result.kind}"
    return ""


def collect_rank_hits(answer: str, aliases: list[str]) -> list[RankHit]:
    lines = logical_lines(answer)
    hits: list[RankHit] = []
    hits.extend(scan_tables(lines, aliases))
    hits.extend(scan_compressed_tables(lines, aliases))
    hits.extend(scan_numbered_lines(lines, aliases))
    hits.extend(scan_heading_sequences(lines, aliases))
    hits.extend(scan_bullet_blocks(lines, aliases))
    hits.extend(scan_inline_phrases(lines, aliases))
    return hits


def choose_rank_hit(hits: list[RankHit]) -> RankHit:
    """Select the earliest rankable context, then the strongest signal there."""
    return sorted(hits, key=lambda h: (h.line_no, -h.confidence, h.rank))[0]


def scan_tables(lines: list[str], aliases: list[str]) -> list[RankHit]:
    hits: list[RankHit] = []
    idx = 0
    while idx < len(lines):
        if "|" not in lines[idx]:
            idx += 1
            continue
        start = idx
        block = []
        while idx < len(lines) and "|" in lines[idx]:
            block.append(lines[idx])
            idx += 1
        hits.extend(scan_table_block(block, start + 1, aliases))
    return hits


def scan_table_block(block: list[str], start_line: int, aliases: list[str]) -> list[RankHit]:
    rows = [split_table_row(line) for line in block if split_table_row(line)]
    if len(rows) < 2:
        return []

    header = rows[0]
    data_rows = []
    for row in rows[1:]:
        joined = "|".join(row)
        if TABLE_SEPARATOR_RE.match("|" + joined + "|"):
            continue
        data_rows.append(row)

    if not data_rows:
        return []

    header_text = " ".join(header)
    explicit_rank_table = any(word in header_text for word in ("排名", "名次", "TOP", "序号"))
    category_table = any(
        word in header_text
        for word in ("分类", "功效", "场景", "需求", "预算", "价格区间", "成分类型", "核心需求")
    )
    hits: list[RankHit] = []
    for row_index, row in enumerate(data_rows, start=1):
        row_text = " | ".join(row)
        if not contains_alias(row_text, aliases):
            continue

        explicit = parse_any_rank(row[0]) or parse_leading_rank(row_text)
        if explicit:
            rank = explicit
            confidence = 95
            kind = "table_explicit"
        elif category_table:
            rank = rank_inside_best_cell(row, aliases) or 1
            confidence = 78
            kind = "table_category"
        elif explicit_rank_table:
            rank = parse_any_rank(row[0]) or row_index
            confidence = 90
            kind = "table_ranked"
        else:
            rank = row_index
            confidence = 82
            kind = "table_row_order"
        hits.append(RankHit(rank, confidence, kind, clip(row_text), start_line + row_index))
    return hits


def scan_compressed_tables(lines: list[str], aliases: list[str]) -> list[RankHit]:
    hits: list[RankHit] = []
    for line_no, line in enumerate(lines, start=1):
        if "|" not in line or not contains_alias(line, aliases):
            continue
        rows = split_compressed_table_rows(line)
        if len(rows) < 2:
            continue
        segment_positions = compressed_table_segment_positions(rows)
        for row_index, row in enumerate(rows, start=1):
            row_text = " | ".join(row)
            if not contains_alias(row_text, aliases):
                continue
            explicit = parse_any_rank(row[0]) if row else None
            if explicit:
                hits.append(RankHit(explicit, 93, "compressed_table_explicit", clip(row_text), line_no))
                continue
            if row and contains_alias(row[0], aliases):
                rank = segment_positions[row_index - 1]
                hits.append(RankHit(rank, 88, "compressed_table_row_order", clip(row_text), line_no))
                continue
            local_rank = rank_inside_best_cell(row, aliases)
            if local_rank:
                hits.append(RankHit(local_rank, 76, "compressed_table_cell_order", clip(row_text), line_no))
    return hits


def compressed_table_segment_positions(rows: list[list[str]]) -> list[int]:
    max_width = max((len(row) for row in rows), default=0)
    if not max_width or not any(len(row) < max_width for row in rows):
        return list(range(1, len(rows) + 1))

    positions: list[int] = []
    current = 0
    for row in rows:
        if max_width and len(row) >= max_width:
            current = 1
        else:
            current += 1
        positions.append(current)
    return positions


def split_compressed_table_rows(line: str) -> list[list[str]]:
    chunks = re.split(r"\|\s+\|", line)
    rows: list[list[str]] = []
    for chunk in chunks:
        cells = [
            strip_markdown(cell.strip())
            for cell in chunk.strip().strip("|").split("|")
            if cell.strip()
        ]
        if len(cells) >= 2 and not TABLE_SEPARATOR_RE.match("|" + "|".join(cells) + "|"):
            rows.append(cells)
    return rows


def scan_numbered_lines(lines: list[str], aliases: list[str]) -> list[RankHit]:
    hits: list[RankHit] = []
    for line_no, line in enumerate(lines, start=1):
        if not contains_alias(line, aliases):
            continue
        explicit = parse_leading_rank_for_alias(line, aliases)
        if explicit:
            hits.append(RankHit(explicit, 96, "explicit_number", clip(line), line_no))
    return hits


def scan_heading_sequences(lines: list[str], aliases: list[str]) -> list[RankHit]:
    """Treat repeated markdown item headings inside a section as an ordered list."""
    hits: list[RankHit] = []
    counters: dict[int, int] = {}

    for line_no, line in enumerate(lines, start=1):
        match = MARKDOWN_HEADING_RE.match(line)
        if not match:
            if is_heading_sequence_reset_line(line):
                counters.clear()
            continue

        level = len(match.group(1))
        title = strip_markdown(match.group(2))

        if not is_rankable_heading_item(title):
            for tracked_level in list(counters):
                if tracked_level >= level:
                    del counters[tracked_level]
            continue

        for tracked_level in list(counters):
            if tracked_level > level:
                del counters[tracked_level]
        counters[level] = counters.get(level, 0) + 1
        if not contains_alias(title, aliases):
            continue

        explicit = parse_leading_rank_for_alias(title, aliases)
        rank = explicit or counters[level]
        confidence = 94 if explicit else 87
        kind = "heading_explicit" if explicit else "heading_order"
        hits.append(RankHit(rank, confidence, kind, clip(line), line_no))

    return hits


def is_heading_sequence_reset_line(line: str) -> bool:
    clean = strip_markdown(line).strip()
    if not clean or len(clean) > 180:
        return False
    if clean in {"---", "------"}:
        return True
    if not re.match(r"^[（(]?[0-9一二三四五六七八九十]+[)）.、．]\s*", clean):
        return False
    return bool(
        re.search(
            r"(?:保湿|补水|美白|淡斑|抗氧|抗糖|抗老|抗皱|淡纹|紧致|修护|维稳|控油|祛痘|胶原|视黄醇|胜肽|玻色因|预算|肤质|需求|功效|场景|类型|平价|中端|高端)",
            clean,
        )
    )


def is_rankable_heading_item(title: str) -> bool:
    clean = strip_markdown(title).strip()
    if not clean:
        return False
    if clean in {"一", "二", "三", "四", "五", "六", "七", "八", "九", "十"}:
        return False
    if re.match(r"^[一二三四五六七八九十]+[、.．]\s*", clean):
        return False
    if re.match(r"^(?:[（(]?[一二三四五六七八九十0-9]+[）)]?\s*)?(?:按|分|核心|最终|总结|选购|使用|购买|搭配|避坑|注意|常见|黄金法则)", clean):
        return False
    if clean.endswith(("指南", "法则", "建议", "技巧", "要点", "解析", "对比", "总结")) and not re.search(
        r"(?:精华|次抛|面膜|敷料|修护液|乳液|原液|安瓶|乳|霜|水|棒|品牌)", clean
    ):
        return False
    return True


def scan_bullet_blocks(lines: list[str], aliases: list[str]) -> list[RankHit]:
    hits: list[RankHit] = []
    idx = 0
    while idx < len(lines):
        if not is_bullet_line(lines[idx]):
            idx += 1
            continue
        start = idx
        block = []
        while idx < len(lines) and is_bullet_line(lines[idx]):
            block.append(lines[idx])
            idx += 1
        ranked_context = has_ranked_context(lines, start)
        for item_index, line in enumerate(block, start=1):
            if not contains_alias(line, aliases):
                continue
            if is_combo_recommendation(strip_markdown(line), strip_markdown(line)):
                continue
            explicit = parse_leading_rank_for_alias(line, aliases)
            if explicit:
                hits.append(RankHit(explicit, 92, "bullet_explicit", clip(line), start + item_index))
                continue
            if ranked_context and len(block) > 1:
                hits.append(
                    RankHit(item_index, 90, "bullet_ranked_context", clip(line), start + item_index)
                )
                continue
            local = rank_in_category_clause(line, aliases)
            if local:
                hits.append(RankHit(local, 84, "bullet_category", clip(line), start + item_index))
            else:
                hits.append(RankHit(item_index, 74, "bullet_order", clip(line), start + item_index))
    return hits


def scan_inline_phrases(lines: list[str], aliases: list[str]) -> list[RankHit]:
    hits: list[RankHit] = []
    for line_no, line in enumerate(lines, start=1):
        if not contains_alias(line, aliases):
            continue
        if len(line) > 1400:
            chunks = split_long_line(line)
        else:
            chunks = [line]
        for chunk in chunks:
            if not contains_alias(chunk, aliases):
                continue
            explicit = parse_leading_rank_for_alias(chunk, aliases)
            if explicit:
                hits.append(RankHit(explicit, 86, "inline_explicit", clip(chunk), line_no))
                continue
            local = rank_in_category_clause(chunk, aliases)
            if local:
                confidence = 80 if has_category_signal(chunk) else 68
                hits.append(RankHit(local, confidence, "inline_category", clip(chunk), line_no))
    return hits


def rank_in_category_clause(text: str, aliases: list[str]) -> int | None:
    clean = strip_markdown(text)
    clauses = split_clauses(clean)
    for clause in clauses:
        if not contains_alias(clause, aliases):
            continue
        if is_example_clause(clause):
            continue
        pseudo_table_rank = rank_in_pseudo_table(clause, aliases)
        if pseudo_table_rank:
            return pseudo_table_rank
        after_label = clause
        alias_pos = min(clause.find(alias) for alias in aliases if alias in clause)
        marker_positions = []
        for marker in ("：", ":", "→", "选", "首选", "推荐"):
            pos = clause.rfind(marker, 0, alias_pos)
            if pos != -1:
                if marker in ("：", ":", "→") and not is_rankable_label(clause[:pos]):
                    continue
                marker_positions.append((pos, marker))
        if marker_positions:
            pos, marker = max(marker_positions, key=lambda item: item[0])
            if is_negative_marker_context(clause, pos):
                continue
            candidate = clause[pos + len(marker) :]
            if contains_alias(candidate, aliases):
                after_label = candidate
        if is_combo_recommendation(clause, after_label):
            continue
        after_label = trim_to_local_budget_segment(after_label, aliases)
        parts = split_brand_like_items(after_label)
        matching_positions = [
            index
            for index, part in enumerate(parts, start=1)
            if part and contains_alias(part, aliases) and not is_noise_part(part)
        ]
        if matching_positions:
            if not marker_positions and not has_rankable_item_sequence(parts):
                continue
            return matching_positions[0]
    return None


def is_example_clause(clause: str) -> bool:
    stripped = clause.strip()
    if stripped.startswith(("如", "例如", "比如", "譬如")):
        return True
    if re.fullmatch(r"[^、/|，,]{0,40}等[。.]?", stripped):
        return True
    return False


def is_negative_marker_context(clause: str, marker_pos: int) -> bool:
    before = clause[max(0, marker_pos - 8) : marker_pos]
    return bool(re.search(r"(?:不|别|避免|慎重|谨慎|不建议|不推荐|不宜)\s*$", before))


def has_ranked_context(lines: list[str], block_start: int) -> bool:
    context = " ".join(strip_markdown(line) for line in lines[max(0, block_start - 3) : block_start])
    return bool(RANKED_CONTEXT_RE.search(context))


def is_rankable_label(label: str) -> bool:
    clean = strip_markdown(label)
    clean = re.sub(r"^\s*(?:[-*+•]\s*)?(?:[0-9一二三四五六七八九十]+[.、．]\s*)?", "", clean)
    tail = re.split(r"(?:\s+-\s+| - |—|：|:)", clean)[-1].strip()
    tail = tail.strip(" -_*#[]【】()（）")
    if not tail:
        return False
    if any(non_rank in tail for non_rank in NON_RANK_LABELS):
        return False
    return bool(RANKABLE_LABEL_RE.search(tail) or len(tail) <= 18)


def trim_to_local_budget_segment(text: str, aliases: list[str]) -> str:
    alias_positions = [text.find(alias) for alias in aliases if alias in text]
    if not alias_positions:
        return text
    alias_pos = min(alias_positions)
    matches = [match for match in BUDGET_LABEL_RE.finditer(text) if match.start() < alias_pos]
    if not matches:
        return text
    last = matches[-1]
    return text[last.end() :]


def is_combo_recommendation(clause: str, recommendation_text: str) -> bool:
    if not COMBO_SIGNAL_RE.search(clause):
        return False
    return "+" in recommendation_text or "＋" in recommendation_text or "、" in recommendation_text


def rank_in_pseudo_table(clause: str, aliases: list[str]) -> int | None:
    alias_positions = [clause.find(alias) for alias in aliases if alias in clause]
    if not alias_positions:
        return None
    alias_pos = min(alias_positions)
    table_pos = clause.rfind("表格", 0, alias_pos)
    if table_pos == -1:
        return None
    prefix = clause[table_pos:alias_pos]
    candidates = []
    for match in PRODUCT_LIKE_RE.finditer(prefix):
        candidate = match.group(1)
        if any(noise in candidate for noise in ("产品名称", "代表产品", "修护作用", "使用技巧")):
            continue
        candidates.append(candidate)
    if 0 <= len(candidates) < 30:
        return len(candidates) + 1
    return None


def rank_inside_best_cell(row: list[str], aliases: list[str]) -> int | None:
    for cell in row:
        if not contains_alias(cell, aliases):
            continue
        local = rank_in_category_clause(cell, aliases)
        if local:
            return local
        parts = split_brand_like_items(strip_markdown(cell))
        for index, part in enumerate(parts, start=1):
            if contains_alias(part, aliases):
                return index
    return None


def split_long_line(line: str) -> list[str]:
    chunks = re.split(r"(?:(?:---+)|(?=##\s)|(?=###\s)|[。；;])", line)
    return [chunk.strip() for chunk in chunks if chunk.strip()]


def split_clauses(text: str) -> list[str]:
    clauses = re.split(r"[。；;，\n]|(?:\s-{2,}\s)|(?:\s\|\s)", text)
    return [clause.strip() for clause in clauses if clause.strip()]


def split_brand_like_items(text: str) -> list[str]:
    text = re.sub(r"\([^)]{0,80}\)", "", text)
    text = re.sub(r"（[^）]{0,80}）", "", text)
    text = re.sub(r"\[[^\]]+\]\([^)]+\)", "", text)
    text = text.replace("、", "|").replace("，", "|").replace(",", "|")
    text = text.replace("/", "|").replace("／", "|")
    text = re.sub(r"(?<!\d)\+(?!\d)", "|", text)
    text = re.sub(r"\s+(?:和|与|及|或)\s+", "|", text)
    text = re.sub(r"(?:\*\*|__|`)", "", text)
    return [part.strip(" -_*#[]【】()（）:：") for part in text.split("|")]


def has_rankable_item_sequence(parts: list[str]) -> bool:
    meaningful = [part for part in parts if part and not is_noise_part(part)]
    return len(meaningful) >= 2


def has_category_signal(text: str) -> bool:
    return any(
        signal in text
        for signal in (
            "首选",
            "推荐",
            "选",
            "适合",
            "场景",
            "功效",
            "预算",
            "分类",
            "核心",
        )
    )


def parse_leading_rank(text: str) -> int | None:
    match = LEADING_NUMBERED_RE.search(strip_markdown(text))
    if not match:
        return None
    raw = match.group(1) or match.group(2)
    value = parse_rank_number(raw)
    if value and 0 < value < 100:
        return value
    return None


def parse_leading_rank_for_alias(text: str, aliases: list[str], max_distance: int = 90) -> int | None:
    stripped = strip_markdown(text)
    match = LEADING_NUMBERED_RE.search(stripped)
    if not match:
        return None
    alias_positions = [stripped.find(alias) for alias in aliases if alias in stripped]
    if not alias_positions:
        return None
    alias_pos = min(alias_positions)
    between = stripped[match.end() : alias_pos]
    if alias_pos - match.end() > max_distance:
        return None
    if "：" in between or ":" in between:
        return None
    if any(signal in between for signal in ("首选", "组合", "搭配", "方案", "类型", "需求", "肤质", "场景")):
        return None
    raw = match.group(1) or match.group(2)
    value = parse_rank_number(raw)
    if value and 0 < value < 100:
        return value
    return None


def parse_any_rank(text: str) -> int | None:
    for match in ANY_NUMBERED_RE.finditer(strip_markdown(text)):
        raw = match.group(1) or match.group(2)
        value = parse_rank_number(raw)
        if value and 0 < value < 100:
            return value
    return None


def parse_rank_number(raw: str) -> int | None:
    raw = raw.strip()
    if raw.isdigit():
        return int(raw)
    if raw == "十":
        return 10
    if raw.startswith("十") and len(raw) == 2:
        return 10 + CHINESE_NUMBERS.get(raw[1], 0)
    if raw.endswith("十") and len(raw) == 2:
        return CHINESE_NUMBERS.get(raw[0], 0) * 10
    if "十" in raw and len(raw) == 3:
        return CHINESE_NUMBERS.get(raw[0], 0) * 10 + CHINESE_NUMBERS.get(raw[2], 0)
    return CHINESE_NUMBERS.get(raw)


def contains_alias(text: str, aliases: Iterable[str]) -> bool:
    return any(alias and alias in text for alias in aliases)


def first_matching_line(lines: list[str], aliases: list[str]) -> str:
    for line in lines:
        if contains_alias(line, aliases):
            return line
    return ""


def is_bullet_line(line: str) -> bool:
    return bool(LIST_START_RE.match(line.strip()))


def split_table_row(line: str) -> list[str]:
    stripped = line.strip()
    if not stripped.startswith("|"):
        return []
    cells = [strip_markdown(cell.strip()) for cell in stripped.strip("|").split("|")]
    return cells


def strip_markdown(text: str) -> str:
    text = HEADING_RE.sub("", text)
    text = re.sub(r"!\[[^\]]*\]\([^)]+\)", "", text)
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    text = text.replace("**", "").replace("__", "").replace("`", "")
    return re.sub(r"\s+", " ", text).strip()


def normalize_text(text: str) -> str:
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = text.replace("\u3000", " ")
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text


def logical_lines(text: str) -> list[str]:
    text = normalize_text(text)
    text = re.sub(r"\s*(---+)\s*", r"\n\1\n", text)
    text = re.sub(r"\s+(#{1,6}\s+)", r"\n\1", text)
    text = re.sub(r"(?<![0-9])\s+([0-9]{1,2}[.、．]\s+(?![0-9]))", r"\n\1", text)
    text = re.sub(r"\s+([-*+•]\s+(?=[^\n]{0,90}[：:]))", r"\n\1", text)
    return [line.strip() for line in text.splitlines() if line.strip()]


def is_noise_part(part: str) -> bool:
    part = part.strip()
    if not part:
        return True
    if re.fullmatch(r"[0-9<>元 -]+", part):
        return True
    return len(part) <= 1


def cell_text(value: object) -> str:
    if value is None:
        return ""
    return str(value)


def read_headers(worksheet) -> dict[str, int]:
    headers: dict[str, int] = {}
    for col in range(1, worksheet.max_column + 1):
        value = worksheet.cell(row=1, column=col).value
        if value is not None:
            headers[str(value).strip()] = col
    return headers


def resolve_column(spec: str | None, headers: dict[str, int], defaults: Iterable[str]) -> int | None:
    if spec:
        return parse_column_spec(spec, headers)
    for header in defaults:
        if header in headers:
            return headers[header]
    return None


def parse_column_spec(spec: str, headers: dict[str, int]) -> int:
    spec = spec.strip()
    if spec in headers:
        return headers[spec]
    if spec.isdigit():
        return int(spec)
    if re.fullmatch(r"[A-Za-z]+", spec):
        return openpyxl.utils.column_index_from_string(spec.upper())
    raise SystemExit(f"Unknown column spec: {spec}")


def ensure_column(worksheet, spec: str) -> int:
    headers = read_headers(worksheet)
    if spec in headers:
        return headers[spec]
    if spec.isdigit() or re.fullmatch(r"[A-Za-z]+", spec.strip()):
        return parse_column_spec(spec, headers)
    col = worksheet.max_column + 1
    worksheet.cell(row=1, column=col).value = spec
    return col


def find_or_create_output_column(worksheet, header: str, near_col: int) -> int:
    headers = read_headers(worksheet)
    if header in headers:
        return headers[header]

    max_col = worksheet.max_column
    for col in range(near_col + 1, max_col + 2):
        if column_is_empty(worksheet, col):
            worksheet.cell(row=1, column=col).value = header
            return col

    col = max_col + 1
    worksheet.cell(row=1, column=col).value = header
    return col


def column_is_empty(worksheet, col: int) -> bool:
    for row in range(1, worksheet.max_row + 1):
        if worksheet.cell(row=row, column=col).value not in (None, ""):
            return False
    return True


def default_output_path(input_path: Path, brand: str) -> Path:
    return Path.cwd() / "exports" / "brand_ranker" / f"{input_path.stem}_{brand}排名.xlsx"


def dedupe_keep_order(values: Iterable[str]) -> list[str]:
    seen = set()
    out = []
    for value in values:
        if value in seen:
            continue
        seen.add(value)
        out.append(value)
    return out


def clip(text: str, limit: int = 260) -> str:
    text = strip_markdown(text).replace("\n", " ")
    return text if len(text) <= limit else text[: limit - 1] + "…"


if __name__ == "__main__":
    raise SystemExit(main())
